#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-tbb-soname12
Version  : 2021.5.0
Release  : 35
URL      : https://github.com/01org/tbb/archive/v2021.5.0/tbb-2021.5.0.tar.gz
Source0  : https://github.com/01org/tbb/archive/v2021.5.0/tbb-2021.5.0.tar.gz
Summary  : C++ library for parallel programming on multi-core processors.
Group    : Development/Tools
License  : Apache-2.0
Requires: compat-tbb-soname12-lib = %{version}-%{release}
Requires: compat-tbb-soname12-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : mesa-dev
BuildRequires : pkg-config
BuildRequires : python3

%description
# oneAPI Threading Building Blocks
[![Apache License Version 2.0](https://img.shields.io/badge/license-Apache_2.0-green.svg)](LICENSE.txt) [![oneTBB CI](https://github.com/oneapi-src/oneTBB/actions/workflows/ci.yml/badge.svg)](https://github.com/oneapi-src/oneTBB/actions/workflows/ci.yml?query=branch%3Amaster)

%package lib
Summary: lib components for the compat-tbb-soname12 package.
Group: Libraries
Requires: compat-tbb-soname12-license = %{version}-%{release}

%description lib
lib components for the compat-tbb-soname12 package.


%package license
Summary: license components for the compat-tbb-soname12 package.
Group: Default

%description license
license components for the compat-tbb-soname12 package.


%prep
%setup -q -n oneTBB-2021.5.0
cd %{_builddir}/oneTBB-2021.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1640911300
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
%cmake ..
make  %{?_smp_mflags}  DEFAULTFLAGS="$CFLAGS"
popd

%install
export SOURCE_DATE_EPOCH=1640911300
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-tbb-soname12
cp %{_builddir}/oneTBB-2021.5.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/compat-tbb-soname12/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/libtbbmalloc.so.2
rm -f %{buildroot}*/usr/lib64/libtbbmalloc.so.2.5
rm -f %{buildroot}*/usr/lib64/libtbbmalloc_proxy.so.2
rm -f %{buildroot}*/usr/lib64/libtbbmalloc_proxy.so.2.5
rm -f %{buildroot}*/usr/include/oneapi/tbb.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/blocked_range.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/blocked_range2d.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/blocked_range3d.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/blocked_rangeNd.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/cache_aligned_allocator.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/collaborative_call_once.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/combinable.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_hash_map.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_lru_cache.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_map.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_priority_queue.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_queue.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_set.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_unordered_map.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_unordered_set.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/concurrent_vector.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_aggregator.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_aligned_space.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_allocator_traits.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_assert.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_concurrent_queue_base.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_concurrent_skip_list.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_concurrent_unordered_base.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_config.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_containers_helpers.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_exception.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_export.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_body_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_cache_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_indexer_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_item_buffer_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_join_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_node_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_node_set_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_nodes_deduction.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_tagged_buffer_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_trace_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_flow_graph_types_impl.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_hash_compare.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_intrusive_list_node.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_machine.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_mutex_common.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_namespace_injection.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_node_handle.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_pipeline_filters.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_pipeline_filters_deduction.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_range_common.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_rtm_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_rtm_rw_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_scoped_lock.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_segment_table.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_small_object_pool.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_string_resource.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_task.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_task_handle.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_template_helpers.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_utils.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/detail/_waitable_atomic.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/enumerable_thread_specific.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/flow_graph.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/flow_graph_abstractions.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/global_control.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/info.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/memory_pool.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/null_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/null_rw_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/parallel_for.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/parallel_for_each.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/parallel_invoke.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/parallel_pipeline.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/parallel_reduce.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/parallel_scan.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/parallel_sort.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/partitioner.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/profiling.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/queuing_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/queuing_rw_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/rw_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/scalable_allocator.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/spin_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/spin_rw_mutex.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/task.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/task_arena.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/task_group.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/task_scheduler_observer.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/tbb_allocator.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/tbbmalloc_proxy.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/tick_count.h
rm -f %{buildroot}*/usr/include/oneapi/tbb/version.h
rm -f %{buildroot}*/usr/include/tbb/blocked_range.h
rm -f %{buildroot}*/usr/include/tbb/blocked_range2d.h
rm -f %{buildroot}*/usr/include/tbb/blocked_range3d.h
rm -f %{buildroot}*/usr/include/tbb/blocked_rangeNd.h
rm -f %{buildroot}*/usr/include/tbb/cache_aligned_allocator.h
rm -f %{buildroot}*/usr/include/tbb/collaborative_call_once.h
rm -f %{buildroot}*/usr/include/tbb/combinable.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_hash_map.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_lru_cache.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_map.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_priority_queue.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_queue.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_set.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_unordered_map.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_unordered_set.h
rm -f %{buildroot}*/usr/include/tbb/concurrent_vector.h
rm -f %{buildroot}*/usr/include/tbb/enumerable_thread_specific.h
rm -f %{buildroot}*/usr/include/tbb/flow_graph.h
rm -f %{buildroot}*/usr/include/tbb/flow_graph_abstractions.h
rm -f %{buildroot}*/usr/include/tbb/global_control.h
rm -f %{buildroot}*/usr/include/tbb/info.h
rm -f %{buildroot}*/usr/include/tbb/memory_pool.h
rm -f %{buildroot}*/usr/include/tbb/null_mutex.h
rm -f %{buildroot}*/usr/include/tbb/null_rw_mutex.h
rm -f %{buildroot}*/usr/include/tbb/parallel_for.h
rm -f %{buildroot}*/usr/include/tbb/parallel_for_each.h
rm -f %{buildroot}*/usr/include/tbb/parallel_invoke.h
rm -f %{buildroot}*/usr/include/tbb/parallel_pipeline.h
rm -f %{buildroot}*/usr/include/tbb/parallel_reduce.h
rm -f %{buildroot}*/usr/include/tbb/parallel_scan.h
rm -f %{buildroot}*/usr/include/tbb/parallel_sort.h
rm -f %{buildroot}*/usr/include/tbb/partitioner.h
rm -f %{buildroot}*/usr/include/tbb/profiling.h
rm -f %{buildroot}*/usr/include/tbb/queuing_mutex.h
rm -f %{buildroot}*/usr/include/tbb/queuing_rw_mutex.h
rm -f %{buildroot}*/usr/include/tbb/scalable_allocator.h
rm -f %{buildroot}*/usr/include/tbb/spin_mutex.h
rm -f %{buildroot}*/usr/include/tbb/spin_rw_mutex.h
rm -f %{buildroot}*/usr/include/tbb/task.h
rm -f %{buildroot}*/usr/include/tbb/task_arena.h
rm -f %{buildroot}*/usr/include/tbb/task_group.h
rm -f %{buildroot}*/usr/include/tbb/task_scheduler_observer.h
rm -f %{buildroot}*/usr/include/tbb/tbb.h
rm -f %{buildroot}*/usr/include/tbb/tbb_allocator.h
rm -f %{buildroot}*/usr/include/tbb/tbbmalloc_proxy.h
rm -f %{buildroot}*/usr/include/tbb/tick_count.h
rm -f %{buildroot}*/usr/include/tbb/version.h
rm -f %{buildroot}*/usr/lib64/cmake/TBB/TBBConfig.cmake
rm -f %{buildroot}*/usr/lib64/cmake/TBB/TBBConfigVersion.cmake
rm -f %{buildroot}*/usr/lib64/cmake/TBB/TBBTargets-relwithdebinfo.cmake
rm -f %{buildroot}*/usr/lib64/cmake/TBB/TBBTargets.cmake
rm -f %{buildroot}*/usr/lib64/libtbb.so
rm -f %{buildroot}*/usr/lib64/libtbbmalloc.so
rm -f %{buildroot}*/usr/lib64/libtbbmalloc_proxy.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/tbb.pc
rm -f %{buildroot}*/usr/share/doc/TBB/README.md

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtbb.so.12
/usr/lib64/libtbb.so.12.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-tbb-soname12/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
